//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nFacturae.Tests.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nFacturae.Tests.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;fe:Facturae xmlns:fe=&quot;http://www.facturae.es/Facturae/2007/v3.1/Facturae&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt;
        ///  &lt;FileHeader&gt;
        ///    &lt;SchemaVersion&gt;3.1&lt;/SchemaVersion&gt;
        ///    &lt;Modality&gt;I&lt;/Modality&gt;
        ///    &lt;InvoiceIssuerType&gt;EM&lt;/InvoiceIssuerType&gt;
        ///    &lt;Batch&gt;
        ///      &lt;BatchIdentifier&gt;A99887723392009-&lt;/BatchIdentifier&gt;
        ///      &lt;InvoicesCount&gt;1&lt;/InvoicesCount&gt;
        ///      &lt;TotalInvoicesAmount&gt;
        ///        &lt;TotalAmount&gt;468.10&lt;/TotalAmount&gt;
        ///      &lt;/TotalInvoicesAmount&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_31 {
            get {
                return ResourceManager.GetString("sample_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;fe:Facturae xmlns:fe=&quot;http://www.facturae.es/Facturae/2009/v3.2/Facturae&quot; xmlns:ds=&quot;http://www.w3.org/2000/09/xmldsig#&quot;&gt; 
        ///  &lt;FileHeader&gt;
        ///    &lt;SchemaVersion&gt;3.2&lt;/SchemaVersion&gt;
        ///    &lt;Modality&gt;I&lt;/Modality&gt;
        ///    &lt;InvoiceIssuerType&gt;EM&lt;/InvoiceIssuerType&gt;
        ///    &lt;Batch&gt;
        ///      &lt;BatchIdentifier&gt;0000000000B18&lt;/BatchIdentifier&gt;
        ///      &lt;InvoicesCount&gt;1&lt;/InvoicesCount&gt;
        ///      &lt;TotalInvoicesAmount&gt;
        ///        &lt;TotalAmount&gt;63.13&lt;/TotalAmount&gt;
        ///      &lt;/TotalInvoicesAmount&gt;
        ///      &lt;TotalOutstan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sample_32 {
            get {
                return ResourceManager.GetString("sample_32", resourceCulture);
            }
        }
    }
}
